# -*- coding: utf-8 -*-
"""python programming task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQzRuLnyBoQeDlogY3ggAehJt2z29wVK

# 1.Here is a sample line of code that can be executed in Python:
## print("Hello, World!")

# You can just as easily store a string as a variable and then print it to stdout:
## my_string = "Hello, World!"
## print(my_string)

# The above code will print Hello, World! on your screen. Try it yourself in the editor below!

# Input Format
## You do not need to read any input in this challenge.

# Output Format
## Print Hello, World! to stdout.

# Sample Output 0
## Hello, World!
"""

print("Hello, World!")

"""# 2.Python If-Else Task

# Objective  
## Print **Weird** if the number is weird. Otherwise, print **Not Weird**.

# Rules  
## A number is considered *Weird* if:  
### The number is **odd**,  
### OR the number is **even** and **in the range 6 to 20** (inclusive).

## A number is **Not Weird** if:  
### It is **even** and **in the range 2 to 5** (inclusive),  
### OR it is **even** and **greater than 20**.

# Input Format  
## A single integer **n**.

# Constraints  
### 1 ≤ n ≤ 100

# Output Format  
## Print **Weird** or **Not Weird** based on the conditions.

# Sample Input 0  
### 3

# Sample Output 0  
### Weird

# Sample Input 1  
### 24

# Sample Output 1  
### Not Weird
"""

k = int(input())

if k % 2 == 1:
    print("Weird")
elif 2 <= k <= 5:
    print("Not Weird")
elif 6 <= k <= 20:
    print("Weird")
else:
    print("Not Weird")

"""# 3.Arithmetic Operators Task

# Objective
## Read two integers, a and b, from STDIN.
## Print three lines:
### 1. The sum of a and b.
### 2. The difference of a and b (first - second).
### 3. The product of a and b.

# Example
## a = 3
## b = 5

### Output:
#### 8
#### -2
#### 15

# Input Format
## The first line contains the first integer, a.
## The second line contains the second integer, b.

# Constraints
## 1 ≤ a ≤ 10^10
## 1 ≤ b ≤ 10^10

# Output Format
## Print the three results on separate lines:
### a + b
### a - b
### a * b

# Sample Input 0
### 3
### 2

# Sample Output 0
### 5
### 1
### 6

# Explanation
### 3 + 2 = 5
### 3 - 2 = 1
### 3 * 2 = 6
"""

a = int(input())
b = int(input())

print(a + b)
print(a - b)
print(a * b)

"""# 4.Python Division Task

# Objective
## Read two integers, a and b, from STDIN.
## Print two lines:
### 1. Integer division result: a // b
### 2. Float division result: a / b

# Description
## No rounding or formatting is required.
## Just print the raw results.

# Example
## a = 3
## b = 5

### Results:
#### Integer division: 3 // 5 = 0
#### Float division: 3 / 5 = 0.6

# Input Format
## The first line contains the integer a.
## The second line contains the integer b.

# Output Format
## Print:
### a // b  
### a / b  

# Sample Input 0
### 4
### 3

# Sample Output 0
### 1
### 1.33333333333
"""

a = int(input())
b = int(input())

print(a // b)
print(a / b)

"""# 5.Python Loops Task

# Objective
## Read an integer n from STDIN.
## For all non-negative integers i < n, print i².

# Example
## n = 3
### The list of integers less than 3 is: [0, 1, 2]
### Their squares are:
#### 0
#### 1
#### 4

# Input Format
## A single integer n.

# Constraints
## 1 ≤ n ≤ 20

# Output Format
## Print n lines.
### Each line contains i² for i in the range 0 to n-1.

# Sample Input 0
### 5

# Sample Output 0
### 0
### 1
### 4
### 9
### 16
"""

k = int(input())

for i in range(k):
    print(i * i)

"""# 6.Leap Year Function Task

# Objective
## Determine whether a given year is a leap year.
## If it is a leap year, return True.
## Otherwise, return False.

# Rules (Gregorian Calendar)
## A year is a leap year if:
### 1. It is evenly divisible by 4
#### EXCEPT when it is divisible by 100
##### UNLESS it is also divisible by 400

# Meaning:
## ✔ Years like 2000, 2400 are leap years.
## ✘ Years like 1800, 1900, 2100, 2200, 2300, 2500 are NOT leap years.

# Task
## Complete the function is_leap(year):
### Return True if the year is a leap year.
### Otherwise, return False.

# Input Format
## A single integer:
### year — the year to test.

# Constraints
## 1900 ≤ year ≤ 10⁵

# Output Format
## The function must return a Boolean value:
### True
### or
### False

# Sample Input 0
### 1990

# Sample Output 0
### False

# Explanation
### 1990 is not divisible by 4 → Not a leap year.
"""

def is_leap(year):
    if year % 400 == 0:
        return True
    if year % 100 == 0:
        return False
    if year % 4 == 0:
        return True
    return False

year = int(input())
print(is_leap(year))

"""# 7.Print Function Task

# Objective
## Read an integer n from STDIN.
## Without using string methods, print the numbers:
### 1 2 3 ... n
## As a single string with no spaces.

# Example
## n = 5
### Output string: 12345

# Input Format
## A single integer n.

# Constraints
## 1 ≤ n ≤ 150

# Output Format
## Print the list of integers from 1 to n as a single string.
### No spaces
### No separators

# Sample Input 0
### 3

# Sample Output 0
### 123

"""

def print_numbers(n):
    for i in range(1, n + 1):
        print(i, end='')

n = int(input())
print_numbers(n)

